STDCELLS += and2_b
STDCELLS += and2_c
STDCELLS += buf_b
STDCELLS += buf_c
STDCELLS += buf_d
STDCELLS += dff_b
STDCELLS += dffr_b
STDCELLS += inv_a
STDCELLS += inv_b
STDCELLS += inv_c
STDCELLS += inv_d
STDCELLS += nand2_b
STDCELLS += nor2_b
STDCELLS += or2_b
STDCELLS += or2_c
STDCELLS += xor2_a
STDCELLS += tie0_b
STDCELLS += tie1_b
STDCELLS += nwsx
STDCELLS += fill1
STDCELLS += fill2
STDCELLS += decap5
STDCELLS += decap6
STDCELLS += decap7
STDCELLS += decap8

# CELLS += mtc2
# CELLS += nor2_a
# CELLS += nor2_c
# CELLS += nor2_d
# CELLS += nand2_c
# CELLS += and2_c
# CELLS += subc_2
# CELLS += dly_c
# CELLS += dly_c_nosub
# CELLS += dly_test
# CELLS += cap_tc1
# CELLS += cap_tc2
# CELLS += cap_tc3
# CELLS += cap_tc4
# CELLS += res_tc1
# CELLS += devcap 
# # CELLS += temp2
# # CELLS += dlm_tc1
# # CELLS += PadInC
# # CELLS += pad_driver
# # CELLS += pad_m2
# # CELLS += bond75
# CELLS += schmitt
# CELLS += schmitt_1V
# # CELLS += padinv
# # CELLS += pad_io_top
# # CELLS += pad_io_bot
# # CELLS += pad_io
# # CELLS += pad_in_top
# # CELLS += pad_in_bot
# # CELLS += pad_x0_top
# # CELLS += pad_xtal
# # CELLS += pad_nwellres
# # CELLS += nwell_res
# # CELLS += padio
# # CELLS += myPadOut
# # CELLS += inv_b_nosub
# # CELLS += inv_b_bigsd
# # # CELLS += dffposx1
# # # CELLS += xor2x1
# # # CELLS += dff_d_v2
# # # CELLS += dff_d_v3
# # # # CELLS += dffr_d
# # # CELLS += and2_b
# # # CELLS += ckgen_b
# # # CELLS += dlyinv_b
# # # CELLS += dlybuf_b
# # # CELLS += xnor2_b
# # # # CELLS += tmp_b
# # # # CELLS += tmp2_b
# # # # CELLS += dlyrc_7ns
# # # # CELLS += tmp3_b
# # # # CELLS += exp1
# # CELLS += and2_b
# # CELLS += ckgen_b
# # CELLS += dlyinv_b
# # CELLS += dlybuf_b
# # # CELLS += tmp_b
# # CELLS += tmp2_b
# # CELLS += dlyrc_7ns
# # CELLS += tmp3_b
